services:
  - type: web
    name: movie-explorer-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5001

  - type: static
    name: movie-explorer-frontend
    env: node
    buildCommand: |
      # Install root dependencies
      npm install
      # Install and build backend
      cd backend
      npm install
      cd ..
      # Install and build frontend
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://movie-explorer-backend.onrender.com 